theme = "kanagawa"

[editor]
bufferline = "multiple"
color-modes = true
line-number = "relative"
rulers = [80]
true-color = true
completion-timeout = 5

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "â”†"
render = true

[editor.soft-wrap]
enable = true


[editor.statusline]
left = ["mode", "file-name", "read-only-indicator",
 "file-modification-indicator","separator","spacer", "version-control"]
center = ["spinner"]
right = ["diagnostics","primary-selection-length", "position"]


[editor.lsp]
display-inlay-hints = false
display-messages = true

[keys.normal]
"A-c" = ":bc"
"space" = {"o"="file_picker_in_current_buffer_directory"}
